#!/usr/bin/env bash

if [ ! -f ~/.config/distrobox.ini ]; then
    echo "No distrobox config at ~/.config/distrobox.ini, skipping"
    exit 0
fi

notify-send "Azure Distrobox" "Updating distroboxes" -u NORMAL
distrobox assemble create --file ~/.config/distrobox.ini
notify-send "Azure Distrobox" "Finished updating distroboxes" -u NORMAL
